- name: Ensure OpenSSl and libssl are the latest versions
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache=yes force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - meld 
    - mercurial
  tags: packages